package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/BurntSushi/toml"
	"github.com/caarlos0/env/v11"
)

type config struct {
	Title                  string `env:"TITLE"`
	MessageOnConnection    string `env:"MESSAGE_ON_APPEARANCE"`
	MessageOnDisconnection string `env:"MESSAGE_ON_DISAPPEARANCE"`
	DetectConnection       bool   `env:"DETECT_APPEARANCE"`
	DetectDisconnection    bool   `env:"DETECT_DISAPPEARANCE"`
	Verbose                bool   `env:"VERBOSE"`
}

var defaultConfig = config{
	Title:                  "Port Notifier",
	MessageOnConnection:    "Connected: %s",
	MessageOnDisconnection: "Disconnected: %s",
	DetectConnection:       true,
	DetectDisconnection:    true,
}

func loadAndParseConfig() config {
	var cfg config
	var found bool
	var searchPath = []string{
		"./config.toml",
		"~/.config/port-notifier/config.toml",
	}

	for _, p := range searchPath {
		log.Debugf("attempting to load config from %s", p)

		abs, err := filepath.Abs(p)
		if err != nil {
			log.Debugf("failed to find the absolute path for %s", p)
			continue
		}
		_, err = os.Stat(abs)
		if err != nil {
			log.Debugf("failed to stat a config file %s", abs)
			continue
		}
		if _, err := toml.DecodeFile(abs, &cfg); err != nil {
			log.Debugf("failed to decode a config file %s", abs)
			continue
		}

		log.Infof("loaded a config file: %s", p)
		found = true
		break
	}

	if !found {
		log.Debugf("no config file found, falling back to defaults")
		cfg = defaultConfig
	}

	err := env.Parse(&cfg)
	if err != nil {
		log.Errorf("failed to parse env config: %s", err)
	}

	return cfg
}

func generateConfig() error {
	f, err := os.Create("config.toml")
	if err != nil {
		return err
	}
	defer f.Close()

	e := toml.NewEncoder(f)
	err = e.Encode(defaultConfig)
	if err != nil {
		return err
	}

	_, err = f.Write([]byte(fmt.Sprintf("\n# Generated by Port Notifier %s\n", version)))
	if err != nil {
		return err
	}

	return nil
}
